### ISSUE TITLE
背景画像のコントラスト調整

### ISSUE THREAD

**Issue by mshr1-create** [mshr1-create/greentea-samplesite#13]
### 1. 概要
各ページで設定している背景画像の明度や色調がページごとにバラつき、上に重ねるテキストやボタンの可読性にムラが生じている。各背景画像にダーク／ライトのオーバーレイを適用し、どのページでも文字・CTAがはっきり見えるように統一する。

### 2. 背景（Why）

- ページによっては背景が明るすぎて白テキストが読みにくい
- 逆に暗い背景だと黒テキストが背景に埋もれる
- ブランディング上の統一感も損なわれ、アクセシビリティ（WCAG AA）基準を満たせていない

### 3. 目的（What）

1. 可読性確保：テキスト／ボタンのコントラスト比をWCAG AA（最低4.5:1）以上にする
2. デザインの一貫性：全ページで「背景＋オーバーレイ＋コンテンツ」というレイヤー構成を共通化
3. アクセシビリティ強化：視覚に課題を持つユーザーにも読みやすい表示を提供

### 4. 受け入れ基準（Definition of Done）

- すべての背景付きページで、テキスト（見出し／リード文／CTAボタン）のコントラスト比が4.5:1以上を達成
- ダークオーバーレイ（例：rgba(0,0,0,0.4)）／ライトオーバーレイ（例：rgba(255,255,255,0.4)）のどちらかをCSSクラスで適用し、必要に応じて切り替え可能
- デザインシステムに「.bg-overlay--dark」「.bg-overlay--light」のユーティリティクラスを追加
- モバイル・タブレット・PCすべてでレイアウト崩れなく、パフォーマンスに著しい影響なし
- 各ページでのスクリーンショットを取得し、コントラスト比検証ツール（Chrome DevTools / axe-core など）で合格していることを証明

### 5. 実装タスク（How）

1. デザイン検討
- 各ページの代表的な背景画像（トップ／会社案内／季節のおすすめ／商品一覧／お問い合わせ）をピックアップ
- 画面モック上で「暗めオーバーレイ」「明るめオーバーレイ」を当て比べ、最適な透過量を決定

2. CSS拡張
- デザインシステム（SCSS／Tailwind 設定など）に以下のユーティリティクラスを追加
```css
.bg-overlay--dark {
  position: relative;
}
.bg-overlay--dark::before {
  content: "";
  position: absolute; inset: 0;
  background-color: rgba(0, 0, 0, 0.4);
}
.bg-overlay--light {
  position: relative;
}
.bg-overlay--light::before {
  content: "";
  position: absolute; inset: 0;
  background-color: rgba(255, 255, 255, 0.4);
}
```

- テキスト／ボタン要素は、.bg-overlay--dark > * で z-index を確保

3. マークアップ修正

各ページの <section> ないし <header> 要素に適切なクラス（dark or light）を付与

例：
```
<section class="page-header bg-cover bg-overlay--dark">
  <h1 class="page-title">こだわりの茶畑から、最高の一杯を</h1>
</section>
```

4, コントラストチェック
Chrome DevTools のレポート、axe-core などで各ページの主要テキスト部分を検証
スクリーンショットを成果物として添付し、レビュー担当者へ提出
