### ISSUE TITLE
レスポンシブ対応

### ISSUE THREAD

**Issue by mshr1-create** [mshr1-create/greentea-samplesite#7]
### 概要
PC、タブレット、スマートフォンなどデバイスに応じたレスポンシブ対応を行う

### 設計

- 小型デバイス スマートフォン
幅の目安: 320px ～ 575px
```CSS
/* 小さな端末用 (幅 320px ～ 575px) */
@media (max-width: 575px) {
    /* フォントサイズの調整や余白の縮小、縦並びレイアウトなど */
    body {
        font-size: 14px;
    }
    .container {
        padding: 0 10px;
    }
}

```

- 中型デバイス スマートフォン
幅の目安: 576px ～ 767px
```CSS
/* 中型スマホ用 (幅 576px ～ 767px) */
@media (min-width: 576px) and (max-width: 767px) {
    body {
        font-size: 15px;
    }
    .container {
        padding: 0 15px;
    }
}

```

- タブレット
幅の目安: 768px ～ 991px
```CSS
/* タブレット用 (幅 768px ～ 991px) */
@media (min-width: 768px) and (max-width: 991px) {
    body {
        font-size: 16px;
    }
    .container {
        max-width: 750px;
        margin: 0 auto;
    }
}

```

- デスクトップ・ラップトップ
幅の目安: 1200px以上
```CSS
/* 大型デスクトップ用 (幅 1200px以上) */
@media (min-width: 1200px) {
    .container {
        max-width: 1170px;
        margin: 0 auto;
    }
}

```
